[package]
name = "hms_project"
version = "0.0.1"
authors = ["dd"]
edition = "2018"

[dependencies]
actix-web = "3"
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0"}
actix-cors = "0.5.4"